// For User Action/Reducer Type
export const USER_TYPE = {
    UPDATE_STATE: 'UPDATE_USER_STATE',
  
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILUTE: 'LOGIN_USER_FAILUTE',
  
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  
    CHECKIN_USER: 'CHECKIN_USER',
    CHECKIN_USER_SUCCESS: 'CHECKIN_USER_SUCCESS',
    CHECKIN_USER_FAILURE: 'CHECKIN_USER_FAILURE',
  
    CHECKOUT_USER: 'CHECKOUT_USER',
    CHECKOUT_USER_SUCCESS: 'CHECKOUT_USER_SUCCESS',
    CHECKOUT_USER_FAILURE: 'CHECKOUT_USER_FAILURE',
  
    BEGINVISIT_USER: 'BEGINVISIT_USER',
    BEGINVISIT_USER_SUCCESS: 'BEGINVISIT_USER_SUCCESS',
    BEGINVISIT_USER_FAILURE: 'BEGINVISIT_USER_FAILURE',
  
    ENDVISIT_USER: 'ENDVISIT_USER',
    ENDVISIT_USER_SUCCESS: 'ENDVISIT_USER_SUCCESS',
    ENDVISIT_USER_FAILURE: 'ENDVISIT_USER_FAILURE',
  
    UPLOADSCANNEDTAG_USER: 'UPLOADSCANNEDTAG_USER',
    UPLOADSCANNEDTAG_USER_SUCCESS: 'UPLOADSCANNEDTAG_USER_SUCCESS',
    UPLOADSCANNEDTAG_USER_FAILURE: 'UPLOADSCANNEDTAG_USER_FAILURE',
    
    PATROL_USER: 'PATROL_USER',
    PATROL_USER_SUCCESS: 'PATROL_USER_SUCCESS',
    PATROL_USER_FAILURE: 'PATROL_USER_FAILURE',
  
    INCIDENT_USER: 'INCIDENT_USER',
    INCIDENT_USER_SUCCESS: 'INCIDENT_USER_SUCCESS',
    INCIDENT_USER_FAILURE: 'INCIDENT_USER_FAILURE',
  
  };